export { default as CapaHomeTemplate } from './CapaHomeTemplate.vue'
export { default as CapaBibliastemplate } from './CapaBibliastemplate.vue'
export { default as Livrostemplate } from './Livrostemplate.vue'
export { default as CapitulosTemplate } from './CapitulosTemplate.vue'
export { default as VersoTemplate} from './VersoTemplate.vue'